### ISSUE TITLE
Unexpected keyword argument 'data'

### ISSUE THREAD

**Issue by JorgeBarredo14** [Riscure/python-trsfile#39]
When connecting to a Lecroy oscilloscope, line 130 _traceFile.append(trsfile.Trace(trsfile.SampleCoding.BYTE, channel_out, data=data_output))_ outputs the following error:

ERROR:  __init__() got an unexpected keyword argument 'data'

**Comment by TomHogervorst** [comment]
The 'data' argument of the Trace constructor has been deprecated since version 2.0.0. It is recommended that you use a TraceParameterMap instead. A TraceParametersMap has replaced the data field because the map contains meta-data on the type and purpose of the data in the trace. 
If your data contains solely output data, you could use a TraceParameterMap like this:

`trace_params = trsfile.TraceParameterMap()
trace_params.add_parameters("OUTPUT", data_output)
traceFile.append(trsfile.Trace(trsfile.SampleCoding.BYTE, channel_out, parameters=trace_params))`

**Comment by TomHogervorst** [comment]
As an additional note: Pull request #38, which is currently in review, will add a replacement of the deprecated 'data' argument named 'raw_data'. This will be part of the next version of this library.

**Comment by JorgeBarredo14** [comment]
Hi Tom! The code works well now, but _trace_params = trsfile.TraceParameterMap()_ provides the error _module 'trsfile' has no attribute 'TraceParameterMap'_. I have tried to solve it by linking the method TraceParameterMap once imported the library _trsfile_, but it does not solve the issue.

**Comment by TomHogervorst** [comment]
My apologies, I thought that that map was included in the imports done with `import trsfile`, but it is not. 
You can add the import `from trsfile.parametermap import TraceParameterMap` and then use ` trace_params = TraceParameterMap()'
