### ISSUE TITLE
Data retrieval from trsfile

### ISSUE THREAD

**Issue by edaho1** [Riscure/python-trsfile#41]
I've been searching for a way to retrieve data from the trsfile similar to the Matlab version,
`traceset.get(0).getData()` 
 but I have yet to find it. I'm new to python so I might have missed it. If it exists, can someone push me in the right direction, please? If not, will it be added in the future, or is it not on the agenda?

**Comment by matthijsgeers-riscure** [comment]
Hi edaho,

I'm assuming the data you're referring to is the metadata saved with each trace, which usually contains input/output data. Of note is that, since version 2.0 of both libraries (Java and Python), we migrated to a more descriptive metadata system. This data is now saved in a map containing key-value pairs, which makes it explicit what each piece of data (or parameter) means, in addition to making it easily expandable with other parameters. You don't _have_ to use this functionality though, as it's still possible to dump the metadata as a byte array.

It appears that we do not have a convenience function to retrieve the parameter data from a `Trace` object (noted, we might want to add this). Fortunately, this is Python, where everything is public and anything goes! As such, we can directly access the `TraceParameterMap` that is created when a `Trace` is initialized: `traceset[0].parameters`. This object can be printed to see what parameters it contains, but if you haven't used the new metadata feature to create your trace set, chances are that it will only contain "LEGACY_DATA". Either way, any `TraceParameterMap` can be dumped as a byte array by calling `serialize()` on it.

I believe that combining the two functions should be equivalent to the Java statement that you posted:
`traceset[0].parameters.serialize()`

If you have any more questions, please don't hesitate to ask!

**Comment by edaho1** [comment]
Worked like a charm, thank you.
